### ISSUE TITLE
Title color instead of indicator

### ISSUE THREAD

**Issue by szalaidaniel** [ladmini/LZViewPager#1]
Hi!

I would like title color black when active and gray when inactive the page (instead of use indicator).

`        button.setTitleColor(UIColor.black, for: .selected)
        button.setTitleColor(UIColor.black.withAlphaComponent(0.2), for: .normal)`

This code is working, but my first/ main page title will black/active only when I tap. How can I make the first title "button" active default (100% black)?

Thanks

**Comment by ladmini** [comment]
Have you ever tried
```swift
if index == 0 {
   button.isSelected = true
}
```

So the whole code looks like this:
```swift 
func button(at index: Int) -> UIButton {
        let button = UIButton()
        button.setTitleColor(UIColor.black, for: .selected)
        button.setTitleColor(UIColor.black.withAlphaComponent(0.2), for: .normal)
        if index == 0 {
            button.isSelected = true
        }
        return button
    }
}
```

<img width="352" alt="image" src="https://user-images.githubusercontent.com/5718706/41214321-5b1f0f2e-6d7d-11e8-8c68-974b65676491.png">

BTW, if you don't want to show the indicator you can Implementing the following method
```swift
func shouldShowIndicator() -> Bool {
   return false
}
```

**Comment by szalaidaniel** [comment]
It's working! Thank you.
