### ISSUE TITLE
Cannot load underlying module for 'LZViewPager' 

### ISSUE THREAD

**Issue by sergiocasero** [ladmini/LZViewPager#16]
Hello guys, I'm facing this issue only with a custom build configuration, we have:

Debug: Everything is OK
PRE: KO, we get Cannot load underlying module for 'LZViewPager'
Release: Everything is OK
Any help? Thanks for your job!

**Comment by ladmini** [comment]
Sorry, I don't know how to solve this problem.

**Comment by sergiocasero** [comment]
I think that this a problem with the podspec file or something, is the unique pod that faces this issue

**Comment by sergiocasero** [comment]
@ladmini I'd found the and was another legacy lib that was broking everything hahaha. Sorry for the issue opening :(
