### ISSUE TITLE
Header isn't scrolling

### ISSUE THREAD

**Issue by chaimgross** [ladmini/LZViewPager#17]
<img width="423" alt="Screen Shot 2020-07-15 at 13 35 09" src="https://user-images.githubusercontent.com/23248206/87535455-34bba080-c6a0-11ea-8f6c-6ee029983c8a.png">
Following demo, but for some reason header isn't scrolling.
On version 1.2.5 Xcode 11.5
if you need any code please let me know

**Comment by muneebzain** [comment]
I want that code, I am using 6 controllers and my buttons in the header are cutting.
