### ISSUE TITLE
Header tabs disappear when you change the app direction to be left to right  

### ISSUE THREAD

**Issue by MostafamShuman** [ladmini/LZViewPager#18]

**Comment by ladmini** [comment]
You mean when you rotate the screen from left to right, header tabs disappears, right?  Do you have the example code?

**Comment by MostafamShuman** [comment]
yes exactly, it's just a part of a live project.
I just use LZWiewPager with MOLH library so 
<img width="989" alt="Screen Shot 2020-09-10 at 1 05 14 PM" src="https://user-images.githubusercontent.com/16261054/92721483-7433ff80-f366-11ea-8078-b2f327606148.png">

**Comment by ladmini** [comment]
I'am sorry, because there is no code, I'm not sure what the problem is. I think you can debug the view hierarchy. In addition, you can also test that there is no problem with the demo provided by me.

**Comment by ghost** [comment]
I'm facing the same problem reported by @MostafamShuman . Any update on this, please?

**Comment by zahraa1994** [comment]
Same problem here , did anyone fix this ?

**Comment by zahraa1994** [comment]
Adding this method fixed the problem for me:
func buttonsAligment() -> ButtonsAlignment {
        return .center
    }

**Comment by HarshParekh03** [comment]
> I'am sorry, because there is no code, I'm not sure what the problem is. I think you can debug the view hierarchy. In addition, you can also test that there is no problem with the demo provided by me.

Hii did you got the solution?? If yes, can you share here?

**Comment by ladmini** [comment]
maybe duplicate #34  duplicate #37
