### ISSUE TITLE
Programmatically Select Tab doesn't work.

### ISSUE THREAD

**Issue by darkhorse-coder** [ladmini/LZViewPager#2]
Hi @ladmini 
Thank you for your pager. Great!
How can i use select(index: Int)? I have used a viewpager in a viewpager. How can i redirect to parent other tab from child / child viewController.
`func select(index: Int)`
don't working. https://d.pr/i/diSUpn
I am sorry my bad english.

**Comment by ladmini** [comment]
Hi zhiyilee,
Thank you very much for raising this issue. The reason for this issue is that I modified hierarchical structure of heardView in the previous version. Now I've fixed it.  Could you please try it again?

**Comment by darkhorse-coder** [comment]
It's working well. thanks for your work. 👍 
And other issue is not working by `pod install`. It is just working `manual install`. :) 
I have an other question. How to disable swipe pagination for a special page?

**Comment by ladmini** [comment]
I tested pod install and it can work properly, could you please add my QQ to communication? QQ:260483162

**Comment by ladmini** [comment]
If your pod doesn't work properly, maybe your pod repository needs to be updated. You can try 

```ruby
pod repo update
```
and then execute 
```ruby 
pod install
```
About how to disable swipe pagination for a special page, maybe I will consider adding this feature in the next version.
