### ISSUE TITLE
how to change Indicator Not Selected Area Color

### ISSUE THREAD

**Issue by kumarlav0** [ladmini/LZViewPager#22]
By Default, it shows White Color for Indicator Which is Not Selected.
![Screenshot 2020-12-17 at 4 25 17 PM](https://user-images.githubusercontent.com/58595312/102479615-21649500-4085-11eb-8e1f-53b48152e239.png)
I want to Change the Color Of the UnSelected area or I want to make its color Clear.
How to do it. I am not Getting any solution for that.
Please help me as soon as possible.

**Comment by ladmini** [comment]
You cannot set color of the unselected area directly, You can set the background color of the header to meet your requirements
```swift
func backgroundColorForHeader() -> UIColor {
        return .clear
}
```
