### ISSUE TITLE
retain cycle by the delegate & dataSource

### ISSUE THREAD

**Issue by AkiLee89** [ladmini/LZViewPager#23]
delegate 和dataSource 沒有宣告成weak 導致 memory leak，麻煩修正一下

**Comment by gavingt** [comment]
The solution here is to mark the following properties as "weak":

`delegate` and `dataSource` in `LZViewPager.swift`
`pagerDelegate` and `dataSource` in `LZViewPagerHeader.swift`
`delegate`, `dataSource`, and `hostController` in `LZViewPagerContent.swift`

Perhaps some of these are not necessary, but it worked for me.
