### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [ladmini/LZViewPager#3]
Good day @ladmini  I am a graphic designer and i would like to contribute to your good project by designing a logo for it. I'll be doing it for free if you will allow me Sir..Thanks and best regards! 
-Tobaloidee

**Comment by ladmini** [comment]
Hi Tobaloidee,
Yes, Please. Thank you very much!

**Comment by Tobaloidee** [comment]
Thanks for the response! Will start designing now and show it here..

**Comment by Tobaloidee** [comment]
Hi @ladmini 

here's what i came up with..The design shows the elements of page view with Tab bar on top and initials "L & Z" of the project for a more personalized approach..I made 3 design options to choose from. Please let me know which is it and if you have any suggestions.

![pres-01](https://user-images.githubusercontent.com/36028424/42429658-ec23d6da-836c-11e8-8d70-5e5fe4152861.png)

**Comment by ladmini** [comment]
Hi @Tobaloidee 
I'm a little busy today.  So sorry for my delays in replying to you.
I appreciate your hard working. They're all very nice.  👍
If let me choose, I prefer the first one.
One of my little suggestion is whether we can also render the first picture in two colors?  I also very like the green color in the 2nd and 3th pictures
Thanks again!

**Comment by Tobaloidee** [comment]
Surely @ladmini  I will edit it and show you here..

**Comment by Tobaloidee** [comment]
here i made 3 versions of the design you picked..I added the orange in the choices..I also put it in dark background for you to see.

If you have decided with one of those I will make a PR and upload it and put it in the readme file. 

![pres-2-01](https://user-images.githubusercontent.com/36028424/42464555-f68ea252-83db-11e8-9c63-9dbd317d0014.png)

**Comment by ladmini** [comment]
Hi @Tobaloidee 

Thank you for working so late. I asked my colleagues to discuss it this morning. The result of our vote was the first one in the first version. 

<img width="410" alt="image" src="https://user-images.githubusercontent.com/5718706/42484900-c15ff486-8427-11e8-9bcd-fed8093bb1ac.png">


By the way, they praised your design ideas very much.  👍

**Comment by Tobaloidee** [comment]
Wow! That was nice to know... :) i will prepare the files and upload it thru PR and also update the readme..thanks thanks!

**Comment by Tobaloidee** [comment]
Here's the PR #4 @ladmini  i am very glad to have contributed here..Thanks so much!
