### ISSUE TITLE
App Crash when comes to LZVewPage Screen 

### ISSUE THREAD

**Issue by Taimoor20** [ladmini/LZViewPager#31]
I am using this library in my project and whenever I run my app it is giving me the following error:

> Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIView 0x7fccc110d3e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key `dataSource.'`

**Comment by ladmini** [comment]
It seems that this is the error of your project itself. Generally, if your outlet is associated with the wrong object, it will have such an error. Please check it.
