### ISSUE TITLE
App crashed | The views aren't loading (unexpectedly found nil)

### ISSUE THREAD

**Issue by C0DE-RUNNER** [ladmini/LZViewPager#33]
Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

<img width="985" alt="Screenshot 2022-10-10 at 2 06 48 PM" src="https://user-images.githubusercontent.com/43192929/194825318-2504f94a-5543-436e-b543-338ea9965a6a.png">

<img width="605" alt="Screenshot 2022-10-10 at 1 58 50 PM" src="https://user-images.githubusercontent.com/43192929/194824078-b7ae7d2b-9412-43bb-94ad-3e780b9b9c6f.png">

**Comment by ladmini** [comment]
It seems to be your own code issue.
