### ISSUE TITLE
Can't change for indicator height

### ISSUE THREAD

**Issue by timemake** [ladmini/LZViewPager#35]
Hi,
I was using the function below but it didn't work.

 - func heightForIndicator(at index: Int)

Please let me know if I miss anything.
Thanks,

**Comment by ladmini** [comment]
I tried it and it works. If there are still any issues, can you send out your code snippets and running results?

<img width="723" alt="截屏2023-05-02 14 34 17" src="https://user-images.githubusercontent.com/5718706/235587076-92cbd1e2-6ff9-4933-9f01-e94618922921.png">
