### ISSUE TITLE
LZViewPager doesn't support localization

### ISSUE THREAD

**Issue by HarshParekh03** [ladmini/LZViewPager#37]
I've used this library for pageviewcontroller and now im facing issue as i also have localization in my app so when i switch to arabic that is from right to left. The LZViewPager just disappears from navigation bar place. For reference i already used the below code in the same viewcontroller file. But it isnt working. Reply expected as soon as possible. As i have used this in a important project

func buttonsAlignment() -> ButtonsAlignment {
            if let lang = Locale.current.languageCode, lang == "ar" || lang == "ur" {
                return .center // i have changed and values and tested
            } else {
                return .center
            }
        }

**Comment by ladmini** [comment]
@HarshParekh03 Can you show me a screenshot of your prototype?
 ButtonsAlignment is used to control the arrangement of buttons on the left、center or right, please refer to the screenshot below

**.left**(default)

<img width="324" alt="截屏2023-05-02 14 19 03" src="https://user-images.githubusercontent.com/5718706/235584847-100b2f47-9d39-4a0f-8ed7-bc1847421c4e.png">

**.center**

<img width="315" alt="截屏2023-05-02 14 19 41" src="https://user-images.githubusercontent.com/5718706/235584929-f0526fe0-d662-425d-901b-4a211f610dbc.png">

**.right**

<img width="316" alt="截屏2023-05-02 14 19 58" src="https://user-images.githubusercontent.com/5718706/235584949-a16a3c55-f7ad-4433-89e3-78edd7946db1.png">

**Comment by HarshParekh03** [comment]
@ladmini 

![EBAFF0D1-22B2-4060-90CA-192C6473A1DE](https://user-images.githubusercontent.com/132267828/235641758-327232c1-8973-4a76-94a7-999d296af7f3.png)
![9E321290-1723-4CAE-8CCA-133FA556B793](https://user-images.githubusercontent.com/132267828/235641785-05b3300c-d2f4-44bb-a86d-9ff6d9673072.png)

Below is the sample code file for your reference that how i use in my project. The button at top disappear on doing RTL.

class PagingVC : UIViewController {
    
    //MARK:- Outlet -
    
    @IBOutlet weak var viewPager: LZViewPager!
    
    //------------------------------------------------------
    
    //MARK:- Class Variable
    
    private var subControllers:[UIViewController] = []
        
    //------------------------------------------------------
    
    //MARK:- Custom Method
    
    fileprivate func applyStyle() {
        self.setBackgroudImage(img: .backImage.image)
    }
    
    fileprivate func setup() {
        self.viewPager.delegate = self
        self.viewPager.dataSource = self
        self.viewPager.hostController = self
        
        let vc1 = CategoryVC.instantiate(fromAppStoryboard: .category)
        let vc2 = ServiceProviderVC.instantiate(fromAppStoryboard: .category)
        vc2.serviceprovider = .serviceprovider
        
        vc1.title = "Category".localized
        vc2.title = "Service Provider".localized
        
        subControllers = [vc1,vc2]
        viewPager.reload()
        
    }
    
    func buttonsAlignment() -> ButtonsAlignment {
            return .center
    }
    
    //------------------------------------------------------
    
    //MARK:- Button Action Method
    
    //------------------------------------------------------
    
    //MARK:- Life Cycle Method
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setup()
        self.applyStyle()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        tabBarController?.tabBar.isHidden = false
        self.navigationController?.navigationBar.isHidden = true
        self.navigationController?.navigationBar.removeShadow()
    }

extension PagingVC: LZViewPagerDelegate, LZViewPagerDataSource {
    func numberOfItems() -> Int {
        return self.subControllers.count
    }
    
    func controller(at index: Int) -> UIViewController {
        return subControllers[index]
    }
    
    func button(at index: Int) -> UIButton {
        let button = UIButton()
        button.setTitleColor(UIColor.black, for: .normal)
        button.setTitleColor(UIColor.appNewYellow, for: .selected)
        button.titleLabel?.font = FontFamily.Mulish.medium.font(size: 16.0)
        button.backGroundColor(color: UIColor.white.withAlphaComponent(0.0))
        return button
    }
    
    func colorForIndicator(at index: Int) -> UIColor {
        return .appNewYellow
    }
    
}

**Comment by HarshParekh03** [comment]
> @HarshParekh03 Can you show me a screenshot of your prototype? ButtonsAlignment is used to control the arrangement of buttons on the left、center or right, please refer to the screenshot below
> 
> **.left**(default)
> 
> <img alt="截屏2023-05-02 14 19 03" width="324" src="https://user-images.githubusercontent.com/5718706/235584847-100b2f47-9d39-4a0f-8ed7-bc1847421c4e.png">
> 
> **.center**
> 
> <img alt="截屏2023-05-02 14 19 41" width="315" src="https://user-images.githubusercontent.com/5718706/235584929-f0526fe0-d662-425d-901b-4a211f610dbc.png">
> 
> **.right**
> 
> <img alt="截屏2023-05-02 14 19 58" width="316" src="https://user-images.githubusercontent.com/5718706/235584949-a16a3c55-f7ad-4433-89e3-78edd7946db1.png">

Please reply to my message it urgent

**Comment by ladmini** [comment]
@HarshParekh03  Sorry because I am on vacation now. I plan to investigate it tomorrow. If you are in a hurry, you can consider debugging its source code. There are only three files in total, which can be referenced manually in the readme.md file (https://github.com/ladmini/LZViewPager/blob/master/README.md#Manually)

**Comment by ladmini** [comment]
@HarshParekh03 
I tried setting system language to Arabic, and the demo works well.

<img width="320" alt="截屏2023-05-04 10 12 03" src="https://user-images.githubusercontent.com/5718706/236084754-6be9d335-91a9-4abf-8a4e-21bd97aa1d15.png">

So my question is：
**1.** Is your language switching within the app or within the system? If it is within the app, which method did you called after switching languages?
**2.** Have you ever tried setting a title for a button like below?

```swift
func button(at index: Int) -> UIButton {
    let button = UIButton()
    button.setTitleColor(UIColor.black, for: .normal)
    button.setTitleColor(UIColor.appNewYellow, for: .selected)
    button.titleLabel?.font = FontFamily.Mulish.medium.font(size: 16.0)
    button.backGroundColor(color: UIColor.white.withAlphaComponent(0.0))
    if index == 1 {
        button.setTitle("Category".localized, for: .normal)
    } else if index == 2 {
        button.setTitle("Service Provider".localized, for: .normal)
    }
    return button
}
```

**Comment by HarshParekh03** [comment]
@ladmini 
1. Switching language is within the app and a method of updating the window is called when the language is switching
2. Yes, i did try setting the button like that but that doesn't work. As i face problem only in RTL languages rest it works fine in all other languages which are LTR.

Below are the code written for reference

--> This is used in choose language screen

func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let obj = self.vm.getLangObjAt(index: indexPath.row)
        self.vm.didSelectLangAt(lang: obj)
        self.tblLanguage.reloadData()
            
        Bundle.main.setAppleLAnguageTo(lang: obj.langCode)
        Lokalise.shared.setLocalizationLocale(Locale(identifier: obj.langCode), makeDefault: false, completion: nil)
        Bundle.main.updateWindow()
    }
    
  ---> Set Language method
    
    func setAppleLAnguageTo(lang: String) {
        guard let languageArray = UserDefaults.standard.value(forKey: UserDefaults.Keys.appleLanguages) as? Array<String>, let languageObj = languageArray.first else { return }
        
        UserDefaults.standard.set([lang, languageObj], forKey: UserDefaults.Keys.appleLanguages)
        UserDefaults.standard.synchronize()
    }
    
-->    And this is the updateWindow method

func updateWindow() {
        if let languageArray = UserDefaults.standard.value(forKey: UserDefaults.Keys.appleLanguages) as? Array<String>, let languageObj = languageArray.first, let language = AppLanguages(rawValue: String(languageObj.prefix(2))) {
            
            switch language {
            case .arabic, .urdu:
                UISearchBar.appearance().semanticContentAttribute = .forceRightToLeft
                UIView.appearance().semanticContentAttribute = .forceRightToLeft
                UIView.userInterfaceLayoutDirection(for: .forceRightToLeft)
                UIView().semanticContentAttribute = .forceRightToLeft
            default:
                UISearchBar.appearance().semanticContentAttribute = .forceLeftToRight
                UIView().semanticContentAttribute = .forceLeftToRight
                UIView.appearance().semanticContentAttribute = .forceLeftToRight
                UIView.userInterfaceLayoutDirection(for: .forceLeftToRight)
            }
        }
        
        DispatchQueue.main.async {
            UIButton.appearance(whenContainedInInstancesOf: [UISearchBar.self]).setTitle("Cancel".localized, for: .normal)
            IQKeyboardManager.shared.toolbarDoneBarButtonItemText = "Done".localized
            UIApplication.shared.manageLogin()
        }
    }

**Comment by ladmini** [comment]
@HarshParekh03 I have reproduced this problem.

**Comment by HarshParekh03** [comment]
@ladmini Alright!
i'm working for the solution too. If you find the solution first please revert back

**Comment by ladmini** [comment]
@HarshParekh03 
I have found the cause of this problem. 
Can you debug it before I release the new version according to the following method? 
if it is resolved, I will release a new version.

**Comment by HarshParekh03** [comment]
@ladmini 
Yes it working perfect now and the issue is resolved.
Thank for your quick assistance.

**Comment by ladmini** [comment]
@HarshParekh03 You are welcome! The new version 1.2.7 has been released.
