### ISSUE TITLE
Header left/right margin and corner radius for indicator

### ISSUE THREAD

**Issue by varunsidpara** [ladmini/LZViewPager#38]
<img width="317" alt="Screenshot 2024-03-08 at 6 21 59 PM" src="https://github.com/ladmini/LZViewPager/assets/19792191/21dc1216-60e4-4a96-9e7c-02f6591b66d3">

Hello, 

I need space on the left side but there is getting issue. Does anyone have a solution for it? Also, do you have a solution for the indicator corner radius?  I want it in a rounded corner.

**Comment by ladmini** [comment]
Please provide a screenshot of your design, how do you expect it to be displayed?

**Comment by varunsidpara** [comment]
<img width="369" alt="Screenshot 2024-03-10 at 6 13 34 PM" src="https://github.com/ladmini/LZViewPager/assets/19792191/c5169510-1269-44ec-9a6f-1ac3a0089805">

I need it like this. with rounded corner indicators.

Thanks

**Comment by ladmini** [comment]
Could you please provide me with the relevant code? which data source and delegate method do you implement?

Rounded corner indicators not supported currently. If you need it, I can update a version to implement it.

**Comment by varunsidpara** [comment]
```
func numberOfItems() -> Int {
        return self.subControllers.count
    }
    
    func controller(at index: Int) -> UIViewController {
        return subControllers[index]
    }
    
    func button(at index: Int) -> UIButton {
        let button = UIButton()
        let title = self.subControllers[index].title ?? ""
        let norAttrStr = NSAttributedString(string: title, attributes: [NSAttributedString.Key.foregroundColor: UIColor.black, NSAttributedString.Key.font: UIFont(name: Utilities.FontName.PoppinsRegular, size: 16)!])
        let selAttrStr = NSAttributedString(string: title, attributes: [NSAttributedString.Key.foregroundColor: UIColor.black, NSAttributedString.Key.font:  UIFont(name: Utilities.FontName.PoppinsSemibold, size: 16)!])

        button.setAttributedTitle(norAttrStr, for: .normal)
        button.setAttributedTitle(selAttrStr, for: .selected)
        return button
    }
    
    func colorForIndicator(at index: Int) -> UIColor {
        return .black
    }

    func widthForButton(at index: Int) -> CGFloat {
        let attributes = [NSAttributedString.Key.font: UIFont(name: Utilities.FontName.PoppinsSemibold, size: 16)]
        let width = (subControllers[index].title ?? "").size(withAttributes: attributes as [NSAttributedString.Key : Any]).width
        return width + 36
    }
    
    func heightForHeader() -> CGFloat {
        return 36
    }
    
    func leftMarginForHeader() -> CGFloat {
        return 24
    }
    
    func rightMarginForHeader() -> CGFloat {
        return 24
    }
    
    func leftMarginForSeparator() -> CGFloat {
        return 24
    }
    
    func rightMarginForSeparator() -> CGFloat {
        return 24
    }
    
    func backgroundColorForHeader() -> UIColor {
        return .clear
    }
    
    func heightForIndicator() -> CGFloat {
        return 5
    }
    
    func shouldShowIndicator() -> Bool {
        return true
    }
    
    func heightForSeparator() -> CGFloat {
        return 1
    }
    
    func colorForSeparator() -> UIColor {
        return Utilities.ColorName.bgColor
    }
    
    func shouldShowSeparator() -> Bool {
        return true
    }
```

This code is currently used for margin. And it will be helpful if you update the code for Rounded corner indicators.

Thanks

**Comment by ladmini** [comment]
Please refer to d0e43cd
```swift
func cornerRadiusForIndicator() -> CGFloat 
```

By the way, some data source and delegate methods are optional and have default values, so you don't need to implement all of them

**Comment by varunsidpara** [comment]
Thanks for adding a corner radius for the indicator. But, still have the same issue for margins.

**Comment by ladmini** [comment]
This issue has been resolved. 
I think you also need to implement this method
```swift
func buttonsAligment() -> ButtonsAlignment {
   .left
}
```
My test results are as follows, for your reference

<img width="340" alt="截屏2024-03-12 19 46 26" src="https://github.com/ladmini/LZViewPager/assets/5718706/b4b81080-4dc6-4608-b3b9-3d3e780fb74c">


Could you please update to the latest version and try again?

**Comment by varunsidpara** [comment]
It's working now... thanks @ladmini
