### ISSUE TITLE
Snapkit with LzViewPager

### ISSUE THREAD

**Issue by AsimSafarli** [ladmini/LZViewPager#39]
8 No such module 'SnapKit'
Missing package product 'SnapKit'

**Comment by ladmini** [comment]
Which methods did you install LZViewPager?  
CocoaPods or Carthage? If CocoaPods, have you try 
```bash
pod repo update
```
before
```bash
pod install
```

**Comment by AsimSafarli** [comment]
i  have already use cocapods but i don't completed this error by the way I change my way . i  have use swift UI

**Comment by ladmini** [comment]
maybe duplicate of #41
