### ISSUE TITLE
I'm getting an error when trying to run a new LZViewPager in my xcode

### ISSUE THREAD

**Issue by tach000** [ladmini/LZViewPager#41]
![Screenshot 2024-07-07 at 12 40 50](https://github.com/ladmini/LZViewPager/assets/41659030/d5685533-69b4-4a82-baa8-fcad3897655b)

Not sure why I am getting this error or how to fix it. I tried also adding the SnapKit dependency and that didn't resolve the issue.

I should specify that I am using the Swift Package Manager.

**Comment by tach000** [comment]
I should specify I am using the Swift Package Manager

**Comment by ladmini** [comment]
Hi tach000
I have tried to fix it. Could you please update to 1.3.2 and try again?

**Comment by tach000** [comment]
I would not mark this completed as I have the latest version and it is still giving me this error. This bug is not fixed.

**Comment by ladmini** [comment]
You may need to remove LZViewPager from SPM and try adding it again? If there are still errors, please tell me some detailed information.

**Comment by tach000** [comment]
I removed it and reinstalled. I even installed SnapKit using SPM. Every time I build I get the same error. What sort of detailed information do you need? I’m happy to provide. 

I’m using the latest XCode on a M1 MacBook Air

**Comment by ladmini** [comment]
You don't need to add additional Snapkit because LZViewPager has already declared a dependency on Snapkit. Could you please provide the detailed error information?

**Comment by tach000** [comment]
I provided a screenshot above.

**Comment by ladmini** [comment]
I just created a new project and add ViewPager (1.3.2) via SMP as a dependency. I imported it in the code and build it without any errors. The following screenshot FYI.
![image](https://github.com/ladmini/LZViewPager/assets/5718706/adf4ec82-14f8-4d2f-b038-2be62e143f4b)

![image](https://github.com/ladmini/LZViewPager/assets/5718706/eb266b8f-b07b-4128-9617-83d728093821)

**Comment by ladmini** [comment]
@tach000 
If there are still errors, I suspect it may be a cache issue with SPM, and you may need to  remove old LZViewPage completely. You don't need add additional SnapKit it will automatically download. If your Xcode doesn't download SnapKit automatically, it may be due to caching issues.

<img width="381" alt="截屏2024-07-08 22 18 27" src="https://github.com/ladmini/LZViewPager/assets/5718706/6c4bba1f-284e-4716-9672-1851e3508895">

**Comment by tach000** [comment]
It seems that my cache error was the issue since Xcode was pulling version 1.3.1; I cleared the cache and re-imported and everything is working perfectly.

Thank you!
