### ISSUE TITLE
同一个ViewPager如何重新加载？

### ISSUE THREAD

**Issue by feelingseas** [ladmini/LZViewPager#43]
如下代码，第一次执行ok，但第二次就不行。

func initViewPager(){
        viewPager.dataSource = self
        viewPager.delegate = self
        viewPager.hostController = self        
        subControllers.removeAll()
        subControllerTitles.removeAll()        
        for i in 1...3{
            let vcItem = ViewControllerTest()
            subControllers.append(vcItem)
            subControllerTitles.append(String(i))
        }
        viewPager.reload()
    }

比如，我一开始，viewpager有5个viewcontroller,然后，我切换显示到第5个viewcontroller。这时，我需要重新显示3个（少于之前的），程序就会报错。代码会在 如下2个地方，产生越界。
其他的index会等于3，在等于3时报错（应该为0，1，2）。感觉是 使用了之前的 最大值5.
func widthForButton(at index: Int) -> CGFloat
 func widthForIndicator(at index: Int) -> CGFloat

感觉应该是个bug哦。

非常感谢有如此好用的viewpager

**Comment by ladmini** [comment]
@feelingseas 
非常感谢你的反馈，我这边尝试了一下你的代码，能够正常运行没有崩溃，请参考下面的录屏
录屏中，启动应用先加载了4个子controller，并选择了第4个，然后在10s以后我按照你上面的代码重新显示3个，能够正常显示。

https://github.com/user-attachments/assets/66f24c35-6d78-4639-a672-978abd03e216


```Swift
func widthForButton(at index: Int) -> CGFloat
func widthForIndicator(at index: Int) -> CGFloat
```
根据你的反馈，上面的代码报错，上面2个方法是LZViewPagerDataSource里面的回调方法，里面执行的是你自己的逻辑，是你自己的逻辑代码越界了吗？如果还有问题，你是否可以给我提供更多的代码片段？

非常感谢！

**Comment by feelingseas** [comment]
@ladmini 
对的，你的视频 这样操作是对的。为什么bug 没复现，没有崩溃，也是因为你的猜测是对的：我在 widthForButton这里 基于index做了一定的处理，也确实是index值越界的问题。比如我当前我做了判断，如果index 大于控制器 数量 -1 就直接返回 0。这样不会出错。。
但逻辑上也不对啊，为什么第一次 index不会越界呢？第二次后 感觉还会引用第一次的count值，不太对吧。。
是不是某些值只计算了一次，没有考虑到第二次计算的情况？
我能力有限，不太会阅读别人的代码哈。你们应该能准确高效解决这个问题哈。

**Comment by ladmini** [comment]
@feelingseas 
还是基于上面的例子我又试了一下，并且我在`widthForButton`方法加了一个日志输出，如下：
```swift
func widthForButton(at index: Int) -> CGFloat {
    print("with for button called at index: \(index)")
    return 100
}
```
结果10s后重新加载打印的日志如下
```log
with for button called at index: 0
with for button called at index: 0
with for button called at index: 1
with for button called at index: 2
with for button called at index: 0
with for button called at index: 0
with for button called at index: 1
with for button called at index: 2
with for button called at index: 0
with for button called at index: 0
with for button called at index: 1
with for button called at index: 2
with for button called at index: 0
with for button called at index: 0
with for button called at index: 0
with for button called at index: 0
with for button called at index: 0
with for button called at index: 1
with for button called at index: 0
with for button called at index: 0
with for button called at index: 0
with for button called at index: 1
with for button called at index: 0
with for button called at index: 2
```
从上面的日志来看，callback回来的index并没有越界。
如果可以的话你是否可以给我一个最简单的示例，我来排查一下？
非常感谢！

**Comment by feelingseas** [comment]
情况说明 ，我发您126邮箱了。

**Comment by ladmini** [comment]
@feelingseas 
你好，邮件已经收到了，非常感谢。
但是我使用您的代码，运行了一下没有crash。我将您的代码做成了一个新的示例，您能对比一下区别在哪里吗？

- 运行示例的方法：
下载最新的代码，运行Target LZViewPagerDemo，程序启动后，首页选择最下面的**Dynamic sub controllers**

所有的代码位于**ViewController10.swift**，这里面几乎都是您的代码，我只是把比如Tools.p注释掉了。
<img width="367" alt="Screenshot 2024-09-19 at 16 56 29" src="https://github.com/user-attachments/assets/60939363-02a2-4a9c-8a7d-81a622d33b7d">

最后附上我的运行录屏：
https://github.com/user-attachments/assets/07e3cc8f-7d3a-4d1e-a630-516a8331ca0f

**Comment by ladmini** [comment]
duplicate #21
