### ISSUE TITLE
如何在父页面,选择要展示的子页面,哪个排第一个

### ISSUE THREAD

**Issue by chinghoi** [ladmini/LZViewPager#5]
这是个好框架,很简洁,最近遇到一个问题,我的父页面有4个按钮,子页面同样也有4个,我想点击对应的按钮进入后自动将该页面显示出来,我在子页面 viewDidLoad 里面添加了`viewPager.select(index: pageViewIndex)` pageViewIndex是定义的全局变量,在父页面跳转的时候改变变量来记录选中了哪个.
这样也可以工作,但是子页面间切换的时候title要闪烁,左右滑动也不是按顺序滑动,所以问下这个该怎么解决呢

**Comment by ladmini** [comment]
非常感谢您的肯定！      
闪烁的原因是调用select的时候我们控件内部是有动画的，viewdidload的时候执行动画是有问题的。我在下一版本中会赠加一个animation 的参数，用户可以决定是不是执行动画，理论上讲可以解决这个问题。
不过换一种方式也能满足你现有的需求，你这个问题可以参考我们demo中的default page，就是在那个buttonAtIndex里面判断index==你父页面传过来的index的时候你设置button.selected应该就可以了。

```swift
func button(at index: Int) -> UIButton {
        let button = UIButton()
        if index == 父页面的index  {
            button.isSelected = true
        }
        return button
    }
}
```
如果还有问题欢迎你继续留言。

**Comment by chinghoi** [comment]
非常感谢,解决问题了.
