### ISSUE TITLE
能否给指示线加一个切换的动画

### ISSUE THREAD

**Issue by yubaokang** [ladmini/LZViewPager#6]
这个框架很类似Android的ViewPager用法，很亲切

但是指示线 在切换的时候有些生硬，作者能否加上一些随着手滑动，线跟着滑动的动画

**Comment by ladmini** [comment]
你的建议非常宝贵，由于不同的需求可能有不同的动画类型，所以这个地方我可能还会考虑下怎么样尽量的通用，我会争取在下一个版本集成该功能，再次感谢！

**Comment by ladmini** [comment]
对不起，暂时没有想到更好的方法，暂时关闭。
