### ISSUE TITLE
LZViewPager Not Obliging by Auto Layout Constraints

### ISSUE THREAD

**Issue by lostinspace247** [ladmini/LZViewPager#7]
Hi,

I'm a recent installer of your library and I ran across an issue where the LZViewPager will not let me create a custom approach, such as modifying the NSLayoutConstraints. I have been trying to create my own layout constraints with the LZViewPager (since my view controller is dynamic) and it won't let me no matter what I do. Here is a snippet of what I am trying to achieve. 

let viewHeader = UIView(frame: CGRect(x: 0, y: 0, width: screenWidth, height: 200))
  var viewPager = LZViewPager(frame: CGRect(x: 0, y: 0, width: screenWidth, height: 100))
  viewPager.translatesAutoresizingMaskIntoConstraints = false

  self.view.addSubview(viewPager)
  self.view.addSubview(viewHeader)
  
  NSLayoutConstraint.activate([ 
       self.viewHeader.topAnchor.constraint(equalTo: self.view.topAnchor, constant: 0),
       self.viewHeader.leadingAnchor.constraint(equalTo: self.view.leadingAnchor, constant: 0),
       self.viewHeader.trailingAnchor.constraint(equalTo: self.view.trailingAnchor, constant: 0),
       self.viewHeader.heightAnchor.constraint(equalToConstant: 200),

       self.viewPager.topAnchor.constraint(equalTo: self.viewHeader.bottomAnchor, constant: 0),
       self.viewPager.leadingAnchor.constraint(equalTo: self.viewHeader.leadingAnchor, constant: 0),
       self.viewPager.trailingAnchor.constraint(equalTo: self.viewHeader.trailingAnchor, constant: 0),
       self.viewPager.bottomAnchor.constraint(equalTo: self.viewHeader.bottomAnchor, constant: 0),
  ])

For some reason the above will not allow me to change the LZViewPager's constraints. No matter correctly done the auto layout is. Can you please apply an update to fix this or assist me with this issue? Thanks

**Comment by ladmini** [comment]
Please provide detailed logs and screenshots.
