### ISSUE TITLE
Pagination Issue.

### ISSUE THREAD

**Issue by afeefSohail** [ladmini/LZViewPager#8]
When i Press Button Fastly of Segments then the Loading of Page Create Issue. Some Time second tab shows ViewController of Third tab ViewController and These Navigation Issue came normaly.

**Comment by JegaJegatheesh** [comment]
Is this show viewcontrollers inside of viewpager

**Comment by ladmini** [comment]
Can not reproduced it in the demo. If there are still issues, please reopen a new issue.
